name: "Push actions"

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Check push
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install setuptools wheel black pytest

      - run: pytthon3 -m black .

      - run: pytthon3 -m pytest